# default constants

TIME = Time.now.strftime('%Y%m%d%H%M%S')
CONFIGFILE_HOSTS = './config/hosts'
VAGRANT_BOX = 'centos-7-6-x64-virtualbox.box'

# build hosts hash

hosts= {}
File.readlines(CONFIGFILE_HOSTS).map(&:chomp).each do |line|
  ipaddr, hostname = line.split(/\s+/)    # only grab first two columns
  hosts[hostname] = ipaddr                # store in hash
  PRIMARY_SYSTEM = hostname if (line =~ /primary/)
end

Vagrant.configure("2") do |config|
  hosts.each do |hostname, ipaddr|
    default = if hostname == PRIMARY_SYSTEM then true else false end
    config.vm.define hostname, primary: default do |node|
      node.vm.box = VAGRANT_BOX
      node.vm.hostname = hostname
      node.vm.network 'public_network', ip: ipaddr
      node.vm.provider('virtualbox') { |vbox| vbox.name = "#{hostname}_#{TIME}" }
      config.vm.provider "virtualbox" do |v|
  v.memory = 2048
  v.cpus = 2
end

    config.vm.provision "ansible_local" do |ansible|
      ansible.become = true
      ansible.become_user = "root"
      ansible.playbook = "playbook.yml"
      ansible.verbose = true
      ansible.install_mode = "pip"
    end
  end


  end
end
